import type {Metadata} from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import React from "react";
import MenuStateProvider from "@/services/MenuStateProvider";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body>
        <MenuStateProvider>
            <Navbar/>
            <Sidebar/>
            {children}
        </MenuStateProvider>
        </body>
        </html>
    );
}
